#!/bin/sh

echo "Scanning staged files for secrets..."

FILES=$(git diff --cached --name-only)

for file in $FILES
do
    if [ -f "$file" ]; then
        if grep -Ei "password|secret|api[_-]?key|access[_-]?key" "$file" >/dev/null
        then
            echo "================================="
            echo "Secret detected in $file"
            echo "Commit blocked!"
            echo "================================="
            exit 1
        fi
    fi
done

echo "No secrets found."
exit 0
